### ISSUE TITLE
Tkinter Issue - Blank SimBA GUI

### ISSUE THREAD

**Issue by charithaomprakash** [sgoldenlab/simba#109]
Hello @sgoldenlab ! 
I am having toruble getting the SimBA GUI to work after installing it via pip install simba-uw-tf-dev. I created a new project, when I try to load the proj_config.ini the GUI window opens, but all the tabs except the ROI are blank (image attached below). Here is the error readout in the Anaconda prompt after loading the proj_config.ini:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/compraka/anaconda3/envs/SimBA/lib/python3.7/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/compraka/anaconda3/envs/SimBA/lib/python3.7/site-packages/simba/SimBA.py", line 3356, in <lambda>
    launchloadprojectButton = Button(lpMenu,text='Load Project',command=lambda:self.launch(lpMenu,inputcommand))
  File "/home/compraka/anaconda3/envs/SimBA/lib/python3.7/site-packages/simba/SimBA.py", line 3367, in launch
    command(self.projectconfigini.file_path)
  File "/home/compraka/anaconda3/envs/SimBA/lib/python3.7/site-packages/simba/SimBA.py", line 3739, in __init__
    self.bp1 = DropDownMenu(label_heatmap,'Bodypart',bpoptions,'15')
  File "/home/compraka/anaconda3/envs/SimBA/lib/python3.7/site-packages/simba/SimBA.py", line 769, in __init__
    self.popupMenu = OptionMenu(self,self.dropdownvar,*self.choices,command=com)
TypeError: __init__() missing 1 required positional argument: 'value'

I also see that this was an issue #71 and tried to see if 'shap' was installed. And it shows me that the requirement is already satisfied. 

Here is the version of SimBA I am currently using:
Name: Simba-UW-tf-dev
Version: 0.77.1

 - OS: Linux
 - Python Version 3.7.0
![Screenshot from 2021-05-10 09-58-14](https://user-images.githubusercontent.com/39599243/117627650-ab1e1780-b178-11eb-9e9b-acfb05ba1c72.png)

**Comment by sgoldenlab** [comment]
Hello @charithaomprakash! This was a bug in earlier versions of SimBA - can you try to update SimBA and see if the error disappears? Try either `pip install simba-uw-tf-dev --upgrade` or `pip install simba-uw-tf == 0.83.6` and let me know how it goes.

**Comment by sgoldenlab** [comment]
Thanks for reporting @charithaomprakash - I will look into it. Can you check one more thing before? This could potentially happen if you have multiple versions of SimBA installed. In you SimBA environment, could you try `pip show simba-uw-tf` and make sure nothing is printed?

**Comment by inoejj** [comment]
@charithaomprakash, using python 3.6 will solve your issue.

**Comment by cameronotto** [comment]
> @charithaomprakash, using python 3.6 will solve your issue.

I am experiencing the same issue on python 3.6.13. I have also ran the update on simba, still nothing. Are there any other solutions? I have created a new environment several times with a fresh install to no avail.

**Comment by inoejj** [comment]
@cameronotto , Try using python 3.6.8 or 3.6.10 and see if it will resolve your issue.

Click on the link below for a step by step guide.

https://simba-docs.readthedocs.io/en/latest/docs/intro/installation.html

If you are still having trouble installing it please let me know and I will try to fix it asap.

Cheers,
JJ

**Comment by cameronotto** [comment]
@inoejj So this did not work again, however I noticed that I am missing FFmpeg. Would this cause this issue, and if so how should I install this?

Thanks so much,
CO

**Comment by inoejj** [comment]
Please send me a screenshot of the error message or providing more details so I can help you out.

Thanks,
JJ

**Comment by cameronotto** [comment]
This is the error that I get. I will try on both those versions. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\mcnuc\anaconda3\envs\simbaenv\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\mcnuc\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 3435, in <lambda>
    launchloadprojectButton = Button(lpMenu,text='Load Project',command=lambda:self.launch(lpMenu,inputcommand))
  File "c:\users\mcnuc\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 3446, in launch
    command(self.projectconfigini.file_path)
  File "c:\users\mcnuc\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 3763, in __init__
    self.severityTarget = DropDownMenu(label_severity,'Target',targetlist,'15')
  File "c:\users\mcnuc\anaconda3\envs\simbaenv\lib\site-packages\simba\SimBA.py", line 775, in __init__
    self.popupMenu = OptionMenu(self,self.dropdownvar,*self.choices,command=com)
TypeError: __init__() missing 1 required positional argument: 'value'

**Comment by inoejj** [comment]
which version of simba are did you install?

What did you type into the terminal?

**Comment by cameronotto** [comment]
@inoejj I followed the exact instructions found in that guide, the version of simba installed is 0.84.3.

I have tried installing developer and non-dev versions and still no luck.

**Comment by cameronotto** [comment]
@inojj I should also clarify, I am installing on windows in Anaconda.

**Comment by inoejj** [comment]
1. create a new environment
2. ` conda install python=3.6.10`
3. `pip install simba-uw-tf-dev`
4. `pip uninstall shapely`
5. `conda install -c conda-forge shapely`

Please follow the steps above and let me know if you still have trouble installing. Or I can do a quick zoom to install it for you :)

**Comment by cameronotto** [comment]
@inoejj Thanks for the help, I have tried these steps several times and no luck. Also on 3.6.8. Could it be that I am missing FFmpeg? How can I install this to my environment or to my device so it works with the environment?

Thanks,
Cameron

**Comment by inoejj** [comment]
FFmpeg does not matter. Please follow the steps below and it should work. In the following example below, you can change `simbaenv` to any name that you wished. 

Else, please send an email to jchoong@uw.edu and I will just do a quick zoom with you :)

https://simba-docs.readthedocs.io/en/latest/docs/intro/installation.html#install-simba-dev-using-anaconda-does-not-support-dlc

**Comment by cameronotto** [comment]
@inoejj If you'd like we can do that, but I have followed these exact instructions several times and no luck. Is it possible I should install an older version of SimBA?

**Comment by inoejj** [comment]
Do you want to type pip show simba-uw-tf-dev and see the version of simba that is installed in your machine?

**Comment by cameronotto** [comment]
@inoejj It installs version 0.84.3 of simba-uw-tf-dev

**Comment by inoejj** [comment]
Please send an email to jchoong@uw.edu and do a quick zoom now.
