### ISSUE TITLE
Install Issue Shapely

### ISSUE THREAD

**Issue by dlhagger** [sgoldenlab/simba#11]
After installing from the requirements.txt, getting the following Traceback:

Traceback (most recent call last):
  File "SimBA.py", line 51, in <module>
    from ROI_freehand_draw_3 import roiFreehand
  File "C:\Users\dlhag\simba\simba\ROI_freehand_draw_3.py", line 6, in <module>
    from shapely.geometry import Polygon
  File "C:\Users\dlhag\Anaconda3\envs\simba\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\dlhag\Anaconda3\envs\simba\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\dlhag\Anaconda3\envs\simba\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\dlhag\Anaconda3\envs\simba\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "C:\Users\dlhag\Anaconda3\envs\simba\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Tried a few shapely versions, couldn't get anything other than this. 

Any thoughts?

**Comment by sgoldenlab** [comment]
Hi @dlhagger - yes, try this one:

Go to the following address and download Shapely 1.7.0: https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

If you are using Python 3.6.0 and windows (as me) click on: Shapely‑1.7.0‑cp36‑cp36m‑win_amd64.whl (or here is a direct link to the file: https://download.lfd.uci.edu/pythonlibs/s2jqpv5t/Shapely-1.7.0-cp36-cp36m-win_amd64.whl)

Next, navigate to the download folder, open a command prompt and run: pip install Shapely-1.7.0-cp36-cp36m-win_amd64.whl 

Let me know if that works

**Comment by dlhagger** [comment]
Hi @sgoldenlab - tried to download directly and still got the same issue. 

I did get it to work by building a python 3.6.10 env and using conda to install shapely, then pip installing the rest of the packages.
