### ISSUE TITLE
"Traceback" error when opening SimBA in the terminal after installing

### ISSUE THREAD

**Issue by RobertoEnrique** [sgoldenlab/simba#126]
I am unable to open SimBA after following guidelines for installation in an Anaconda Environment with Python 3.6.

My system is:
Windows 10 x64bit
Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2601 Mhz, 6 Core(s), 12 Logical Processor(s)

Here is the code:

"(simba-test) C:\Users\pazam>simba
Traceback (most recent call last):
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pazam\anaconda3\envs\simba-test\Scripts\simba.exe\__main__.py", line 4, in <module>
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\simba\SimBA.py", line 8, in <module>
    import deeplabcut
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 19, in <module>
    from deeplabcut.generate_training_dataset.labeling_toolbox import *
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 27, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\utils\__init__.py", line 1, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcut.pose_estimation_tensorflow.config import load_config
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet import *
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\__init__.py", line 14, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\losses.py", line 5, in <module>
    import tensorflow as tf
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "c:\users\pazam\anaconda3\envs\simba-test\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive"

Any ideas why this might be happening?

**Comment by sgoldenlab** [comment]
Hi @RobertoEnrique - yes. 

I think you have installed the simba-uw-tf version, which needs tensorflow. Tensorflow in turn requires cuda and cudnn, which Simba cannot find. I recommend installing the Simba-uw-tf-dev version of SimBA instead, and running the pose-estimation outside of SimBA.

**Comment by RobertoEnrique** [comment]
Thank you so much! I installed simba uw-tf-dev and now it works perfect.

I already have pose estimation from deeplabcut (dlc), so thats good. But
this means that, in the future, If I had simba installed on a gpu with
tensorflow and cuda I could run the dlc labeling and training within simba
instead of having to do them separately?

**Comment by RobertoEnrique** [comment]
Also, a new issue that I am having is:

In the "Import tracking data" window when creating the project, after
having imported 1 single video and specified H5(multi-animal DLC), # of
animals (2), and named each animal, and choosing the tracking type
"ellipse", I choose the path to the h5 file but after clicking on "Import
h5" nothing happens. There is no pop-up window as there should be. Any
ideas why this could be happening?

Best,
Roberto

**Comment by sgoldenlab** [comment]
Hey @RobertoEnrique - yes I recommend keeping them separately. 

Can you check the terminal window, to see if you have any error message there, and paste it here?

**Comment by RobertoEnrique** [comment]
So, the script window on the SimBA GUI says this:

Project "Asty_Aggression_Test1" created in folder "simBA_analysis"
Project "Asty_Aggression_Test1" created in folder "simBA_analysis"
Copying video...
210406_Surface_RC_Males_Match_1_Light.avi copied to
Asty_Aggression_Test1\project_folder\videos\210406_Surface_RC_Males_Match_1_Light.avi
Finished copying video.
Applying settings for multi-animal tracking...
Importing 1 multi-animal DLC h5 files to the current project


It looks as if it is still importing the h5. Then, when I look at the
command line terminal, this is the message that I see:

(simbaenvnotensor) C:\Users\pazam>simba
Exception in Tkinter callback
Traceback (most recent call last):
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\tkinter\__init__.py",
line 1705, in __call__
    return self.func(*args)
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\simba\SimBA.py",
line 3194, in importh5

importMultiDLCpose(self.configinifile,self.h5path.folder_path,self.dropdowndlc.getChoices(),idlist,
self.interpolation.getChoices())
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\simba\read_DLCmulti_h5_function.py",
line 86, in importMultiDLCpose
    currDf = pd.read_hdf(file)
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\pandas\io\pytables.py",
line 384, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\pandas\io\pytables.py",
line 484, in __init__
    tables = import_optional_dependency("tables")
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\pandas\compat\_optional.py",
line 93, in import_optional_dependency
    raise ImportError(message.format(name=name, extra=extra)) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to
install tables.

Not sure where the error is happening. It seems it cannot head the h5,
right?

**Comment by sgoldenlab** [comment]
Your python environment for some reason is missing tables. 

Could you, close SimBA, type `pip install pytables`, and boot up SimBA again and see if it works?

**Comment by RobertoEnrique** [comment]
Hi again,

I did pip install tables and that seemed to work, but the window that pops
up when I click "Import h5" is empty, it's a gray block that says "Define
IDs". When I look into the terminal, it seems as if whatever file it is
reading is too long/big to handle.

Here is the code in the terminal and I also attach a screenshot of what I
am seeing:

Terminal:

(simbaenvnotensor) C:\Users\pazam>simba
Exception in Tkinter callback
Traceback (most recent call last):
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\tkinter\__init__.py",
line 1705, in __call__
    return self.func(*args)
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\simba\SimBA.py",
line 3194, in importh5

importMultiDLCpose(self.configinifile,self.h5path.folder_path,self.dropdowndlc.getChoices(),idlist,
self.interpolation.getChoices())
  File
"C:\Users\pazam\anaconda3\envs\simbaenvnotensor\lib\site-packages\simba\read_DLCmulti_h5_function.py",
line 129, in importMultiDLCpose
    cv2.circle(overlay, (int(x_cord), int(y_cord)), circleScale, currColor,
-1, lineType=cv2.LINE_AA)
OverflowError: Python int too large to convert to C long


SimBA Window Text:


Welcome fellow scientists :)



Project "Aggression_Test3" created in folder "Roberto"
Copying video...
210406_Surface_RC_Males_Match_1_Light.avi copied to
Aggression_Test3\project_folder\videos\210406_Surface_RC_Males_Match_1_Light.avi
Finished copying video.
Applying settings for multi-animal tracking...
Importing 1 multi-animal DLC h5 files to the current project


I am not sure why there is no video.

**Comment by sronilsson** [comment]
`line 129, in importMultiDLCpose
    cv2.circle(overlay, (int(x_cord), int(y_cord)), circleScale, currColor,
-1, lineType=cv2.LINE_AA)
OverflowError: Python int too large to convert to C long`

That's the key line - this is an odd error haven't seen this before. SimBA is trying to convert the x,y coordinate for the body-parts to integers (they are stored as floats in DLC) so we can plot their locations in the image. However the number is too big to be stored as an integer - which really shouldn't happen. Would you mind sharing your dlc h5 file with goldenneurolab@gmail.com and I will take a look at it if there is something odd?

**Comment by RobertoEnrique** [comment]
Sure! I would really appreciate the help! Been trying to make this
DLC/SimBA work in fish and has been pretty uphill. Also... I do have a csv
file that DLC now creates after the filtering step in multianimal tracking
(the new release). In there we have the x-y coordinates for all body
parts/individuals. Maybe there is a way to upload that instead?

Here is the h5:

 210406_Surface_RC_Males_Match_1_LightDLC_resnet...
<https://drive.google.com/file/d/1Pams9egW_SRBgUv1WmVV05u24op29Tpa/view?usp=drive_web>

**Comment by sronilsson** [comment]
Thanks, just saw this, I will try to take a look today.

**Comment by sronilsson** [comment]
Hi @RobertoEnrique - it is the tracking data that you get from DLC that is strange, specifically for animal number 2 - "ind2", looking at this screenshot for example, on the left you se the final body-part for "ind1", the Dorsal_Fin_Tip - all looks well there with x,y pixel-values and likelihoods which are to be expected. 

Then you get to animal 2 - "ind2" and this animals Mouth is located at pixel locations that runs into several billions. This number is too large of an integer so SimBA breaks. I am not sure how this could happen in your pose-estimation end. Judging by the pose-estimation likelihood values for "ind2", I'd say that this animal is also not in the video for the first 7000 frames or so. There are even some negative pixel values in there for "ind2", and this is not possible. 

I would try and clip the video, to remove these first frames when ind2 is not in the video, then analyse it again with pose-estimation followed by SimBA. 

Alternatively, use the DLC filtering functions to remove body-part estimations with low probabilities, then import the data into SimBA using the interpolation functions to fill in the missing values: https://github.com/sgoldenlab/simba/blob/master/docs/Scenario1.md#step-3-import-dlc-tracking-data

![Untitled](https://user-images.githubusercontent.com/34761092/130683287-2dcd0afc-0bb9-493b-8db4-d2e8c779f05a.png)

**Comment by RobertoEnrique** [comment]
Thank you for looking into this! I will follow your suggestions and see if
I get it to work.

Thanks!
-Roberto
