### ISSUE TITLE
File -> Exit Doesn't work

### ISSUE THREAD

**Issue by NickBardjis** [sgoldenlab/simba#145]
In the main Simba window, File -> Exit throws the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\name\anaconda3\envs\conda-environment\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\name\anaconda3\envs\conda-environment\lib\site-packages\simba\SimBA.py", line 971, in Exit
    app.root.destroy()
NameError: name 'app' is not defined

Clicking the red X to close the window works fine.

I am using Windows 10, Python 3.8.5, and I am using Anaconda.

**Comment by inoejj** [comment]
Thank you for reporting this bug. I have fixed it and you can give it a shot by downloading the latest version.

`pip install simba-uw-tf-dev==0.87.8`

Please use python 3.6 for SimBA and let me know if you have any questions.
