### ISSUE TITLE
Error in validating model on single video

### ISSUE THREAD

**Issue by frankiechang123** [sgoldenlab/simba#165]
**Describe the bug**

I'm trying to validate my model on a single video. After selecting one csv file from `features_extracted` and the `sav` model file, an error message shows up when I clicked 'Run model':

```
Running model...
Error: make sure all the videos that are going to be analyzed are represented in the project_folder/logs/video_info.csv file
Predictions generated.
```

**To Reproduce**
1. In GUI, finish previous steps and go to 'Run machine model' tab
2. Select a features file and a sav model file.
2. Click on 'Run Model'
3. See error

**Expected behavior**
- no error message after 'Run Model'
- plot shows up as in the tutorial after clicking 'Generate plot'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu 20.04
 - Python Version [e.g. 3.6.0] 3.6.13
 - Are you using anaconda? Yes
 

**Additional context**
The `video_info.csv`:

```
6,60,756,730,1000,0.6220072346846136
7,60,756,730,1000,0.6220072346846136
4,60,756,730,1000,0.6220072346846136
5,60,756,730,1000,0.6220072346846136
13,60,756,730,1000,0.6220072346846136
2,60,756,730,1000,0.6220072346846136
10,60,756,730,1000,0.6220072346846136
3,60,756,730,1000,0.6220072346846136
12,60,756,730,1000,0.6220072346846136
9,60,756,730,1000,0.6220072346846136
14,60,756,730,1000,0.6220072346846136
8,60,756,730,1000,0.6220072346846136
11,60,756,730,1000,0.6220072346846136
```

**Comment by frankiechang123** [comment]
Also, when I clicked 'Generate Plot', an error message shows up:

![image](https://user-images.githubusercontent.com/51113150/152476833-dede6d80-5103-4a43-821b-e4863d09c78f.png)

It looks like it's looking for an mp4 file while all my videos are in `.avi`? Could this be the problem?

**Comment by sronilsson** [comment]
Hello @frankiechang123 ! Thanks for reporting. 

What might be happening is that your videos are named as integers and there version of SimBA you are running gets confused. I will make sure this doesn't happen, but in meantime, could you rename your files in the video_info.csv, and the files in the `features_extracted` folder, `Video1` etc. instead of `1` and see if that fixes it?

**Comment by frankiechang123** [comment]
Hi! I changed the filenames as you suggested and now there's no error message. 

However, when I clicked 'Generate Plot', it was still looking for `mp4` files. Is there a way around this?

Thank you so much!

**Comment by sronilsson** [comment]
@frankiechang123 - which version of SimBA are you running?

**Comment by sronilsson** [comment]
@frankiechang123 - I've inserted a couple of checks around the functions you are using, could you update SimBA to version 0.89.6 - `pip install simba-uw-tf-dev==0.89.6` or `pip install simba-uw-tf-dev --upgrade` and see if it behaves correctly on your end?

**Comment by frankiechang123** [comment]
Hi! I uninstalled my previous version `simba-uw-no-tf-1.3.0` and installed `simba-uw-tf-dev==0.89`. 

It then says simba cannot be found. What am I doing wrong?

**Comment by sronilsson** [comment]
Hello @frankiechang123 - if you type in your environment:
1) `pip uninstall simba-uw-no-tf` - this removes the simba-uw-no-tf version (which is not maintained)
2) `pip install simba-uw-tf-dev` - this installs the latest version of simba (the one being updated and maintained)
3) `simba` - this should launch simba-uw-tf-dev

let me know if that works

**Comment by Urimons** [comment]
Hey, I encountered the same problem when trying to "Run RF Model" under the "Run machine model" tab, and also when trying to "Analyze machine predictions".
### The error when trying to "Run RF Model": 
_Running 1 model(s) on 4 video file(s).
Analyzing video 1/4...
Error: make sure all the videos that are going to be analyzed are represented in the project_folder/logs/video_info.csv file_
### The error when trying to "Analyze machine predictions": 
_Analyzing video 1/6...
File # processed for machine predictions: 1/6
Error: make sure all the videos that are going to be analyzed are represented in the project_folder/logs/video_info.csv file
Analyzing video 2/6...
File # processed for machine predictions: 2/6
Error: make sure all the videos that are going to be analyzed are represented in the project_folder/logs/video_info.csv file
Analyzing video 3/6...
File # processed for machine predictions: 3/6
Error: make sure all the videos that are going to be analyzed are represented in the project_folder/logs/video_info.csv file
Analyzing video 4/6...
Model paths saved in project_config.ini
Applying settings for classical tracking..._

I tried to apply the suggestions mentioned here with no success... any advice what I should do?

**Comment by sronilsson** [comment]
Hi @Urimons! Which version of SimBA are you running? Can you type `pip show simba-uw-tf-dev` and paste the output here

**Comment by sronilsson** [comment]
Thanks @Urimons - I can see that the function being called hasn't been update for a while. Hang on, I will push a fix.

**Comment by sronilsson** [comment]
@Urimons - can you upgrade SimBA - `pip install simba-uw-tf-dev --upgrade` - it should be version 0.91.0, and check if it works now?

**Comment by Urimons** [comment]
Tried again. The "Run RF model" works now, but the "Analyze..." still doesn't, this is the error:
_Traceback (most recent call last):
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 5878, in <lambda>
    button1 = Button(dlmlabel,text='Analyze',command=lambda:self.findDatalogList(titlebox,var))
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 5888, in findDatalogList
    analyze_process_data_log(self.projectconfigini,finallist)
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\site-packages\simba\process_data_log.py", line 83, in analyze_process_data_log
    firstOccurList.append(round(currDf['Start Time'].min(), 3))
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\site-packages\pandas\core\generic.py", line 11618, in stat_func
    f, name, axis=axis, skipna=skipna, numeric_only=numeric_only
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\site-packages\pandas\core\series.py", line 4090, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "C:\Users\YizharAnalysis\anaconda3\envs\simba\lib\site-packages\pandas\core\nanops.py", line 131, in f
    raise TypeError(e)
TypeError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()._

![image](https://user-images.githubusercontent.com/86400083/162982668-26396011-069d-4aee-be63-a9f818b49884.png)
![image](https://user-images.githubusercontent.com/86400083/162982416-62032ef6-c4e7-49ff-80ce-3dd181d8c4f8.png)

**Comment by sronilsson** [comment]
Can you try again with 0.91.2 and let me know?

**Comment by Urimons** [comment]
it works!
Thanks a lot :)
