### ISSUE TITLE
SIMBA CAN'T START

### ISSUE THREAD

**Issue by mohamedalyzahran** [sgoldenlab/simba#231]
**Describe the bug**
(simbatest) C:\Users\moham>simba
Traceback (most recent call last):
  File "C:\Users\moham\anaconda3\envs\simbatest\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\moham\anaconda3\envs\simbatest\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\moham\anaconda3\envs\simbatest\Scripts\simba.exe\__main__.py", line 4, in <module>
  File "C:\Users\moham\anaconda3\envs\simbatest\lib\site-packages\simba\SimBA.py", line 15, in <module>
    from simba.tkinter_functions import (hxtScrollbar,
  File "C:\Users\moham\anaconda3\envs\simbatest\lib\site-packages\simba\tkinter_functions.py", line 7, in <module>
    from simba.extract_frames_fast import *
  File "C:\Users\moham\anaconda3\envs\simbatest\lib\site-packages\simba\extract_frames_fast.py", line 6, in <module>
    import cv2
  File "C:\Users\moham\anaconda3\envs\simbatest\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

**To Reproduce**
1. Go to 'ENVIRONMENT'
2. Click on 'SIMBA'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Python Version [e.g. 3.6.0] 
 - 3.6.10
 - Are you using anaconda?
 YES

**Additional context**

**Comment by sronilsson** [comment]
Hello @mohamedalyzahran! 

How did you install simba, via pip? Which version of pip do you see with `pip show pip`? If not running version`21.2.2`, could you install this version and see if it runs? 

The error seems to come from opencv not being found. You could also try `pip install opencv-python==3.4.5.20` and see if that fixes it.

**Comment by mohamedalyzahran** [comment]
pip version is 21.2.2 
and i tried pip install opencv-python==3.4.5.20

**Comment by mohamedalyzahran** [comment]
C:\Users\moham>pip install opencv-python==3.4.5.20
Requirement already satisfied: opencv-python==3.4.5.20 in c:\users\moham\anaconda3\envs\test4\lib\site-packages (3.4.5.20)
Requirement already satisfied: numpy>=1.11.3 in c:\users\moham\anaconda3\envs\test4\lib\site-packages (from opencv-python==3.4.5.20) (1.19.5)

**Comment by mohamedalyzahran** [comment]
still have the same issue
C:\Users\moham>simba
Traceback (most recent call last):
  File "C:\Users\moham\anaconda3\envs\test4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\moham\anaconda3\envs\test4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\moham\anaconda3\envs\test4\Scripts\simba.exe\__main__.py", line 4, in <module>
  File "C:\Users\moham\anaconda3\envs\test4\lib\site-packages\simba\SimBA.py", line 15, in <module>
    from simba.tkinter_functions import (hxtScrollbar,
  File "C:\Users\moham\anaconda3\envs\test4\lib\site-packages\simba\tkinter_functions.py", line 7, in <module>
    from simba.extract_frames_fast import *
  File "C:\Users\moham\anaconda3\envs\test4\lib\site-packages\simba\extract_frames_fast.py", line 6, in <module>
    import cv2
  File "C:\Users\moham\anaconda3\envs\test4\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by sronilsson** [comment]
Did you install Simba with pip install simba-uw-tf-dev or simba-uw-tf?

**Comment by mohamedalyzahran** [comment]
simba-uw-tf-dev

**Comment by sronilsson** [comment]
Thanks, googled and seem to be related to specific Windows 10 version? 

https://stackoverflow.com/a/54321350

Can you try with lower opencv version as suggested and let me know how it goes?

**Comment by mohamedalyzahran** [comment]
Thanks alot.
I tried to lower opencv version as suggested and it worked. Many thanks for your help.
