### ISSUE TITLE
DeepLabCut submenu

### ISSUE THREAD

**Issue by mohamedalyzahran** [sgoldenlab/simba#233]
**Describe the bug**
can't find the deeplabcut option in the tracking menu

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10N
 - Python Version [e.g. 3.6.0]
 - Are you using anaconda? yes
 

**Additional context**

**Comment by sronilsson** [comment]
Hi @mohamedalyzahran ! To use deeplabcut in simba, use `simba-uw-tf` rather then `simba-uw-tf-dev`. However, no one maintains that package. DLC and other tools typically have GUI options now, and I recommend using their interfaces rather then the ones present in simba-uw-tf.

**Comment by mohamedalyzahran** [comment]
ok I see
but when i try to pip install simba-uw-tf-dev

I got the following 
ERROR: Cannot install simba-uw-tf and simba-uw-tf==1.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    simba-uw-tf 1.0.3 depends on numpy==1.18.1
    deeplabcut 2.0.9 depends on numpy~=1.14.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by sronilsson** [comment]
Which version of pip do you have? `pip show pip`. Try with `pip install pip==21.2.2`.

**Comment by mohamedalyzahran** [comment]
I am already using Version: 21.2.2

**Comment by sronilsson** [comment]
How about 19.0.1 ? https://github.com/sgoldenlab/simba/issues/186

**Comment by mohamedalyzahran** [comment]
using pip 19.0.1 the installation succeded but I can't stat simba 

here is the error:

(newsimba) C:\Users\moham>simba
Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\platform\self_check.py", line 62, in preload_check
    ctypes.WinDLL(build_info.nvcuda_dll_name)
  File "c:\users\moham\anaconda3\envs\newsimba\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\moham\anaconda3\envs\newsimba\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\moham\anaconda3\envs\newsimba\Scripts\simba.exe\__main__.py", line 5, in <module>
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\simba\SimBA.py", line 8, in <module>
    import deeplabcut
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 19, in <module>
    from deeplabcut.generate_training_dataset.labeling_toolbox import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 27, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\utils\__init__.py", line 1, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcut.pose_estimation_tensorflow.config import load_config
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\__init__.py", line 14, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\losses.py", line 5, in <module>
    import tensorflow as tf
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
    % build_info.nvcuda_dll_name)
ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

**Comment by sronilsson** [comment]
Hi @mohamedalyzahran - that error suggest that DeepLabcut can't find your GPU in your system paths

**Comment by mohamedalyzahran** [comment]
Ok i fixed the problem of the GPU and installed tensorflow in terminal but still have this error

(newsimba) C:\Users\moham>simba
Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "c:\users\moham\anaconda3\envs\newsimba\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\moham\anaconda3\envs\newsimba\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\moham\anaconda3\envs\newsimba\Scripts\simba.exe\__main__.py", line 5, in <module>
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\simba\SimBA.py", line 8, in <module>
    import deeplabcut
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 19, in <module>
    from deeplabcut.generate_training_dataset.labeling_toolbox import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 27, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\utils\__init__.py", line 1, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 38, in <module>
    from deeplabcut.pose_estimation_tensorflow.config import load_config
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 13, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\__init__.py", line 14, in <module>
    from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\losses.py", line 5, in <module>
    import tensorflow as tf
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "c:\users\moham\anaconda3\envs\newsimba\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "c:\users\moham\anaconda3\envs\newsimba\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by sronilsson** [comment]
This is related to the version of TF, simba-uw-tf is build in a dlc version from years ago and require and older version of tf most likely. I will look up which version you need and get back to you.
