### ISSUE TITLE
Error during Outlier correction

### ISSUE THREAD

**Issue by Ejdrup** [sgoldenlab/simba#28]
Setting an outlier correct C similar to described in the documentation (C = 1.5), or any other value causes the SimBA main window to be stuck at:
`Pose-estimation body part setting for outlier correction: 7`
`Processing 1 files for movement outliers...`
While cmd prompts the following:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Ejdrup\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "SimBA.py", line 3981, in correct_outlier
    dev_move_user_defined(configini)
  File "C:\ProgramData\simba\simba\outlier_scripts\movement\correct_devs_mov_user_defined.py", line 115, in dev_move_user_defined
    df_p_cols = pd.DataFrame([csv_df.pop(x) for x in p_cols]).T
  File "C:\Users\Ejdrup\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\frame.py", line 450, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "C:\Users\Ejdrup\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals\construction.py", line 471, in to_arrays
    data, columns, coerce_float=coerce_float, dtype=dtype
  File "C:\Users\Ejdrup\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\internals\construction.py", line 522, in _list_of_series_to_arrays
    indexer = indexer_cache[id(index)] = index.get_indexer(columns)
  File "C:\Users\Ejdrup\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexes\base.py", line 2985, in get_indexer
    "Reindexing only valid with uniquely" " valued Index objects"
pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

**Comment by sgoldenlab** [comment]
Hi @Ejdrup - it appears that multiple columns in the csv has the same name. Let me try and re-create this.

**Comment by Ejdrup** [comment]
Simply deleting the project and recreating made it work. I cannot recreate the situation. You can delete the issue or just close to leave as a possible quick fix for other with similar issues.
