### ISSUE TITLE
Simba not running after install

### ISSUE THREAD

**Issue by KaiserArndt2** [sgoldenlab/simba#375]
**Describe the bug**
I just finished installing simba in anaconda. I tried running simba in the command line and got these errors and simba won't open. I am not sure what to do from here.

**Screenshots**
![image](https://github.com/user-attachments/assets/eb4a399a-32a0-46f3-ae5e-9007eb6e94bb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version 3.11.7
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
Hi @KaiserArndt2 ! 

What version of python image library do you see when you do `pip show pillow`?

Rather than python version 3.11.7, how does it look if you use python 3.6 (recommended), python 3.9 or python 3.10 (if necessary)?

If you stay in python 3.11.7, if you do `pip install pillow=10.3.0`, and then try to restart simba with `simba`, how does it look?

**Comment by KaiserArndt2** [comment]
Hi @sronilsson,

Thank you for the quick reply, I was running in 10.2.0 after running `pip show pillow` (below photo). 
![image](https://github.com/user-attachments/assets/79b14350-43b5-4d62-8098-9cbf41ba57c7)

While still in this version I attempted to run the suggested `pip install pillow=10.3.0`. However simba still didn't open giving these errors.
![image](https://github.com/user-attachments/assets/d8d08dee-e537-4ee0-9eba-7d1681ba832a)


I also attempted to revert back to python version 3.6 and run simba. This didn't work either giving the following errors as well.
![image](https://github.com/user-attachments/assets/b242893f-f3d3-4f13-9e73-9a3dd4d2f9b7)

I didn't try reinstalling simba after any of these attempts, not sure if it would matter. Is this something I should try? 

Thanks for the help!

**Comment by sronilsson** [comment]
Hello @KaiserArndt2 - thanks for testing this. 

In your first screengrab, I see that you are in `base` (outside of the simba conda environment) and there you have Pillow 10.2.1. 

Just to check - when you installed Pillow 10.3.0, did you install it in that base environment, or did you do it in the simba environment after running `conda activate simba` ? 

If you are in Python 3.6, then SimBA should use Pillow 8.3.2 rather than 10.3.0 (I know.. versions can be messy).

If you are in python 3.6, which version of pillow do you see if you do `pip show pillow`? If you do, `pip install pillow==8.3.2` in simba python 3.6 followed by `simba`, does that help?

PS. I have these two lines in the simba python requirements for when you do `pip install simba-uw-tf-dev` to pair different pillow versions to the python version the user is comming from:

```
Pillow==8.3.2; python_version=="3.6"
Pillow==10.3.0; python_version>="3.9"
....
````

**Comment by KaiserArndt2** [comment]
Hi @sronilsson,

I was running in base apparently. But in the simba environment I was on pillow 10.4.0. I tried changing the pillow to 8.3.2 as you suggested. This gave additional errors, but said it installed correctly (image below).

![image](https://github.com/user-attachments/assets/83a4542b-e156-488a-8ab8-db6affb1d9ae)

Attempting to run simba gave new and different errors.

![image](https://github.com/user-attachments/assets/f9544df4-eff9-4d64-aad9-569dd5708bae)

**Comment by sronilsson** [comment]
Got it, there seems to be some tangles in the dependencies... almost there I think :) 

What if you:

i) create a brand new python 3.6 conda environment, 
ii) and then `pip install simba-uw-tf-dev`,
iii) then confirm that you have pillow 8.3.2 with `pip show pillow`, if you dont have it: install it with `pip install pillow==8.3.2`.
iv) launch simba with `simba` ?

**Comment by KaiserArndt2** [comment]
Ok thank you! I got simba to open. Though I got a message saying ffmpeg is not installed, is this important for fully running simba?

**Comment by sronilsson** [comment]
Great, yeah I would get it installed - ffmpeg is very useful and SimBA uses it to perform visualizations and create videos. 

There are some inttructions if you google, e.g., [HERE](https://video.stackexchange.com/questions/20495/how-do-i-set-up-and-use-ffmpeg-in-windows) or [HERE](https://phoenixnap.com/kb/ffmpeg-windows)

**Comment by KaiserArndt2** [comment]
Thank you for the help, I got everything launching without error. But, now when I am making a 'test' project I am getting the following errors when I click the 'create project config' button. The project specifications are in the image bellow. The folder is within a DeepLabCut project folder I have. 
![image](https://github.com/user-attachments/assets/30a11f56-060c-43c7-9257-87dc24a1c9cd)

**Comment by sronilsson** [comment]
Thanks @KaiserArndt2 - I tried to fill in the form just like you, but it ran.. do you see any error messages in the Main SimBA terminal GUI?

**Comment by sronilsson** [comment]
... PS. which version of SImBA do you have?

**Comment by KaiserArndt2** [comment]
Weird, I just relaunched SimBA and did the exact same things and it worked. So not sure what happened.

**Comment by sronilsson** [comment]
> Weird, I just relaunched SimBA and did the exact same things and it worked. So not sure what happened.

#umap-source :)

**Comment by tknopfel** [comment]
I followed this conversion and it helped me to come to a point where launching simba resulted in a brief popup of the SimBA logo which then disappeared. I am new to this and wonder which point I missed.

**Comment by sronilsson** [comment]
Hi @tknopfel ! After the splash screen / pop-up, do you see any error messages / messages  in the terminal from where you launched Simba?

**Comment by tknopfel** [comment]
Hello Simon,

 

Thanks for prompt reply. The below screenshot shows the terminal messages. Not sure it the last is a error message but it indicates that something is missing. There is no directory “/lib/” under the environement.

 

Thomas

**Comment by tknopfel** [comment]
…Version 1.98.9

**Comment by sronilsson** [comment]
Thanks @tknopfel - do you have a screenshot or a copy paste of the error message that includes the lib part? It would be helpful to dig where the error comes from.

**Comment by tknopfel** [comment]
Thanks, below is what I see on the terminal. No red lines/error:
But:
"C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\lib\enum.py" does not exist in my environment", if that matters

(simbaennew) C:\Users\tknopfel>simba
Traceback (most recent call last):
  File "C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\Scripts\simba.exe\__main__.py", line 7, in <module>
  File "C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\lib\site-packages\simba\SimBA.py", line 1098, in main
    app = App()
  File "C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\lib\site-packages\simba\SimBA.py", line 936, in __init__
    self.txt.tag_configure(TagNames.GREETING.value, justify="center", foreground="blue", font=Formats.FONT_LARGE.value)
  File "C:\Users\tknopfel\AppData\Local\anaconda3\envs\simbaennew\lib\enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: FONT_LARGE

**Comment by sronilsson** [comment]
@tknopfel - yeah I'm not sure what it is doing looking in the `lib` directory.. there is no `lib` directory in SimBA. 

I haven't seen this before, one possibility is that it downloaded on your end at the very same time an update was pushed to SimBA perhaps?

If you uninstall simba with `pip uninstall simba-uw-tf-dev` followed by installing it again with `pip install simba-uw-tf-dev`, how does it run then?

**Comment by tknopfel** [comment]
***@***.***> @sgoldenlab/simba

 

Thank you very much!

 

Successfully uninstalled Simba-UW-tf-dev-1.98.9

Successful installed Simab-UW-tf-dev-1.99.3

 

So far so good; simba shows up
