### ISSUE TITLE
Installation of simba error

### ISSUE THREAD

**Issue by ATAICwillbebest** [sgoldenlab/simba#377]
I have followed instructions to install Simba using Anaconda but repeatedly see this error message:

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\86185\AppData\Local\Temp\pip-install-48294r28\simba-uw-tf-dev_f470bf0bbfa84479b125d57df47caf1c\setup.py", line 10, in <module>
          with open("docs/project_description.md", "r", encoding="utf-8") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'docs/project_description.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sronilsson** [comment]
Hi @ATAICwillbebest - thanks for reporting. What python version are you running?
