### ISSUE TITLE
No Behaviors Marked as None?

### ISSUE THREAD

**Issue by kjmartin44** [sgoldenlab/simba#382]
**Describe the bug**
After normal frame labelling in the GUI I attempt to use machine learning but I get an error for apparently having no behaviors marked as None.  However, I do indeed have frames that contain no behavior labels.

**To Reproduce**
1. Label Behavior>Label Behavior
2. Train Machine Model> Train Single Model

SIMBA MISSING COLUMN ERROR: Data for video 20240401SPT35_1-04012024154559 does not contain any annotations for behavior None. Delete classifier None from the SimBA project, or add annotations for behavior None to the video 20240401SPT35_1-04012024154559

**Expected behavior**
The Machine Model Successfully begins training

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.10
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
Hi @kjmartin44! 

This suggest that when SimBA reads in your project_config.ini, to check out what the expected classifier names are, there are some missing values that SimBA doesn't know what to do with, for example. There could be something looking like this: 

![image](https://github.com/user-attachments/assets/1e2f8136-03fd-4a7f-9dbb-119f8ea4a257)


If you drag-and-drop the project_config.ini (you may have to zip it) into this thread I can have a look at it to see where the error could come from?

**Comment by kjmartin44** [comment]
[project_config - Copy.zip](https://github.com/user-attachments/files/16716586/project_config.-.Copy.zip)
 Here is my config.

Thank you

**Comment by sronilsson** [comment]
Got it - thanks. 

Check on line 73 in that file:

![image](https://github.com/user-attachments/assets/d23be6cd-9181-401d-b344-13d49781f013)

It says None. That value is typically set when you set your hyperparameters in this menu: 

![image](https://github.com/user-attachments/assets/8d81e3d2-b0f8-48ef-a7d9-7e1c69bb4498)

You can change it manually in the project_congig, or do it through the GUI and click "SAVE SETTINGS (GLOBAL ENVIRONMENT)" at the bottom of the `MACHINE MODEL SETTING` pop-up. 

Let me know if that makes sense.

**Comment by kjmartin44** [comment]
SIMBA INVALID ML TRAINING SET ERROR: 28 feature columns exist in some files, but missing in others. The feature files are found in the project_folder/csv/targets_inserted directory. SimBA expects all files within the project_folder/csv/targets_inserted directory to have the same number of features: the first 10 column names with mismatches are: ['Movement_Nose', 'Movement_Right Hand', 'Movement_R1', 'Movement_R2', 'Movement_R3', 'Movement_R4', 'Movement_RElbow', 'Movement_RShoulder', 'Movement_Left Hand'] 

 I am now getting this error, I only have one file that has been labelled though so it should not vary.
However, I was having an issue with PIL and I had to downgrade it in order for excel file writing to be correct, but I labelled this file before doing so. should the targets_inserted.csv look almost identical to the deeplabcut inputs? because that is what it looks like for me now.
[20240401SPT35_1-04012024154559.csv](https://github.com/user-attachments/files/16730896/20240401SPT35_1-04012024154559.csv)

**Comment by sronilsson** [comment]
Hi @kjmartin44 - how many files exist within the `project_folder/csv/targets_inserted` directory? Can you send me a screengrab of this directory? 

I can't soenload the CSV. I think you may have to zip it before uploading it here as previously.

**Comment by kjmartin44** [comment]
Here is both the screengrab and the file
[20240401SPT35_1-04012024154559.zip](https://github.com/user-attachments/files/16731069/20240401SPT35_1-04012024154559.zip)

**Comment by sronilsson** [comment]
There are a lot of infs in there for the first 28 features.  That probably has something to do with it, but I am not sure yet why they are there instead of real values. How big is your entire project_folder? If you can share that, maybe through a gdrive link or similar, I can figure out how this has happaned?

**Comment by sronilsson** [comment]
PS. what is the FPS of your video?

**Comment by kjmartin44** [comment]
The project folder is 42 gb. I am uploading it to Drive and can email it to you when it is finished.  My videos are 499 fps

**Comment by sronilsson** [comment]
that's probably where the issues lie, with the FPS...

Speculating but... 
To save on RAM requirements, data gets stored as 32 bit floats in SimBA. Then we want to calculate how much the animals have moved over the last N millisecond... e.g., the code calculates frame-by-frame movement and then aggregates that to the mean / sum over rolling windows. If you have fps of 499 the frame-by-frame movement will be tiny or maybe 0 as a float32 and when aggregated. Then we could get the infs. 

To a human recognize the behaviors you are interested in the videos by eye, is 499 FPS a requirement, if not - do you know what the lower limit is?

**Comment by kjmartin44** [comment]
I was testing out simba to see if I could identify sub-movements within a task as I can with deepethogram.  My animals move so fast that some of the movements are complete within 3 frames at 499 fps so I cannot lower this number.  However, I have some body parts that do not move much while others are incredibly active. Would removing those mostly still tracked body parts possibly help?

**Comment by kjmartin44** [comment]
Or would you recommend editing the videos so that the video is the same but the frame rate is 40 fps, so that the videos are analyzed in slow motion?

**Comment by sronilsson** [comment]
Ah OK, if a behavior is completed within 3 frames at 499 fps, there is no room to resample the videos., thats less than a millisecond i think very short. I'm curios about this, let me troubleshoot with the project and fix infs once I got it and get back to you.

**Comment by kjmartin44** [comment]
I removed all of the body parts that have little to no motion from the csvs and I still have the issue of the inability to read the movement columns because it marks them as 0 or inf.  Have you found any solutions so that I am able to use my data?

**Comment by sronilsson** [comment]
Sorry @kjmartin44 - fell between the chairs thanks for reminding me I'm going to try to replicate your error after setting the FPS to 499

**Comment by sronilsson** [comment]
Hi @kjmartin44 - I gave it a go trying to replicate this error on some 499 FPS projects and I couldn't do it...

Which version of SimBA are you running and can see with `pip show simba-uw-tf-dev` ?

**Comment by kjmartin44** [comment]
I had not used outlier correction before but I can try now. I had opted to skip because its only one animal.
[20240401SPT35_1-04012024154559.zip](https://github.com/user-attachments/files/16949239/20240401SPT35_1-04012024154559.zip)

**Comment by sronilsson** [comment]
No that file looks fine, I don't see any overwhelming amounts of missing values. 

I one last thing, could you share your `project_folder\logs\measures\pose_configs\bp_names\project_bp_names.csv` file? Maybe there is some issues with the headers files.

**Comment by sronilsson** [comment]
OK, one more thing :) What is the pixels per millimeter conversion factor for the video in the `project_folder/logs/video_info.csv` file?

**Comment by kjmartin44** [comment]
I had autopopulated the video parameters with 120 mm but i hadnt set a pixel conversion factor. Do i need to redo everything with the pixel conversion facor in place?

**Comment by sronilsson** [comment]
Ah maybe that could be it, let me see if I get an error like that on my data if the pixels per millimeter conversion factor is missing..

**Comment by sronilsson** [comment]
See how it runs after you make sure this column has a value on your end: 

![image](https://github.com/user-attachments/assets/b9bb2791-5844-45ae-8ae4-b137550f4e76)


I will insert an error msg in the code if its not a valid integer or float value.

**Comment by kjmartin44** [comment]
Do I need to re-run other steps? After fixing that it still is giving me the same error.

**Comment by sronilsson** [comment]
If you click `Skip outlier correction` again and then run feature extraction, do you still see the infs?

**Comment by kjmartin44** [comment]
Yes the infs are still there

**Comment by sronilsson** [comment]
So odd - what is the pixels per millimeter?

**Comment by kjmartin44** [comment]
1.15302. I chose based on what I assumed was a mm in the video but I could be wrong there.

**Comment by kjmartin44** [comment]
would it be best for me to share my whole project folder with you over google drive?

**Comment by sronilsson** [comment]
Thank @kjmartin44  - yes I am having troubles reproducing the infs. I have used a dummy project with what I believe is your project settings (single animal, user-defined pose configuration, 499 FPS, 1.15302 pixels per millimeter) without luck. There maybe something in the data that I overlook.

**Comment by kjmartin44** [comment]
What email would work best to send?  I do not have enough space on my google drive but I can share it over box.

**Comment by sronilsson** [comment]
I think that works, you can share it with sronilsson@gmail.com

**Comment by sronilsson** [comment]
Hi @kjmartin44 thanks for the data looks like a super interesting project. Two things:

i) The project is so big because the frames are extracted for every video. There is no need to do that for any process in SimBA so you could skip that. 

ii) I look at the files inside the `Simba_SPT2\project_folder\csv\features_extracted` directory and I do not see any `infs` or missing values. Can you confirm that this is the case on your end too? Although I can see the infs in the `targets inserted` directory.

**Comment by kjmartin44** [comment]
Thank you.
This is also the case for me, i assume that the infs in the targets inserted are what is causing the issue.  Would copy pasting over the movement values solve my issue?

**Comment by sronilsson** [comment]
Yeah, just to check: If you try to annotate a second video, just a couple of frames here and there, and save those annotations, do you see the infs for the second video too targets inserted directory?

**Comment by sronilsson** [comment]
... would just be halpful to know, if there is something in the code related to the annotations parts that somehow introduced those infs.

**Comment by kjmartin44** [comment]
Im not sure what introduced the infs but reopening and closing labelling seems to have fixed everything.  However my machine learning will not run because of an attribute error.
    self.save_rf_model(self.rf_clf, self.clf_name, self.model_dir_out)
AttributeError: 'TrainRandomForestClassifier' object has no attribute 'rf_clf'

**Comment by sronilsson** [comment]
Do you have a full copy paste of the error msg?

**Comment by kjmartin44** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\site-packages\simba\ui\tkinter_functions.py", line 436, in execute_command
    cmd(**evaluated_kwargs)
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 618, in train_single_model
    model_trainer.save()
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\site-packages\simba\model\train_rf.py", line 386, in save
    self.save_rf_model(self.rf_clf, self.clf_name, self.model_dir_out)
AttributeError: 'TrainRandomForestClassifier' object has no attribute 'rf_clf'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\site-packages\simba\ui\tkinter_functions.py", line 436, in execute_command
    cmd(**evaluated_kwargs)
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\site-packages\simba\SimBA.py", line 618, in train_single_model
    model_trainer.save()
  File "C:\Users\martiki\AppData\Local\anaconda3\envs\simba\lib\site-packages\simba\model\train_rf.py", line 386, in save
    self.save_rf_model(self.rf_clf, self.clf_name, self.model_dir_out)
AttributeError: 'TrainRandomForestClassifier' object has no attribute 'rf_clf'

**Comment by sronilsson** [comment]
What do you see in the SimBA main terminal window GUI before this happens? 

What version of simba do you have installed `pip show simba-uw-tf-dev` ?

**Comment by kjmartin44** [comment]
Reading in 2 annotated files...
Reading complete 20240229SPT1_4-02292024154616 (elapsed time: 0.1385s)...
Reading complete 20240402SPT35_5-04022024155547 (elapsed time: 0.1455s)...
Number of features in dataset: 34
Number of RPull frames in dataset: 1598.0 (15.079999999999998%)
Training and evaluating model...
Reading in 2 annotated files...
Reading complete 20240402SPT35_5-04022024155547 (elapsed time: 0.1406s)...
Reading complete 20240229SPT1_4-02292024154616 (elapsed time: 0.1356s)...
Number of features in dataset: 34
Number of RPull frames in dataset: 1598.0 (15.079999999999998%)
Training and evaluating model...
 and i have 2.0.7

**Comment by sronilsson** [comment]
What did you choose in this dropdown? 
![image](https://github.com/user-attachments/assets/4cdfa308-d615-4aea-b522-b7feb00b7ede)

**Comment by sronilsson** [comment]
If not `RF`, could you set it to RF and try again?

**Comment by kjmartin44** [comment]
It is on RF

**Comment by sronilsson** [comment]
Can you send me the project config again and I will take a look? 
You may have to zip it before you drop it in this thread.

**Comment by kjmartin44** [comment]
[project_config.zip](https://github.com/user-attachments/files/17212722/project_config.zip)
Here it is

**Comment by sronilsson** [comment]
I see nothing odd.. but I'm on my phone and I don't have a computer to test it with. I was caught by hurricane on Friday and no electricity. I will try as soon as I can.
