### ISSUE TITLE
Attribute error during training

### ISSUE THREAD

**Issue by sara-xinyue-liang** [sgoldenlab/simba#385]
**Describe the bug**
I was trying to train a model but it get stuck after completing reading annotated files and showing up an error.

**To Reproduce**
1. Go to "Train machine model" and click on "setting"
2. complete the model setting as I showed in the screen shot
3. close the "machine model setting" and click "Train multiple models"
4. Then I saw that the software stopped after reading annotation data and saw an error in terminal

In main simba page:

----------------
<img width="756" alt="Screenshot 2024-08-28 at 5 49 27 PM" src="https://github.com/user-attachments/assets/23a54126-c88e-4246-b5bd-8f1ae9b2c897">

----------------

In my laptop terminal:

----------------
(simba) saraliang@dhcp-10-29-170-104 ~ % simba
warning||SimBA is not extensively tested beyond python 3.6. You are using python 3.10. If you encounter errors in python>3.6, please report them on GitHub or Gitter (links in the help toolbar) and we will work together to fix the issues!
warning||SimBA could not find a FFMPEG installation on computer (as evaluated by "ffmpeg" returning None). SimBA works best with FFMPEG and it is recommended to install it on your computer
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/saraliang/anaconda3/envs/simba/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/saraliang/anaconda3/envs/simba/lib/python3.10/site-packages/simba/ui/tkinter_functions.py", line 436, in execute_command
    cmd(**evaluated_kwargs)
  File "/Users/saraliang/anaconda3/envs/simba/lib/python3.10/site-packages/simba/SimBA.py", line 622, in train_multiple_models_from_meta
    model_trainer.run()
  File "/Users/saraliang/anaconda3/envs/simba/lib/python3.10/site-packages/simba/model/grid_search_rf.py", line 73, in run
    self.meta_dicts = self.check_validity_of_meta_files(data_df=self.data_df, meta_file_paths=self.meta_file_lst)
  File "/Users/saraliang/anaconda3/envs/simba/lib/python3.10/site-packages/simba/mixins/train_model_mixin.py", line 2182, in check_validity_of_meta_files
    meta_dict[MLParamKeys.UNDERSAMPLE_SETTING.value].lower(),
AttributeError: 'float' object has no attribute 'lower'

----------------

**Screenshots**
My machine model setting
<img width="450" alt="Screenshot 2024-08-28 at 5 11 48 PM" src="https://github.com/user-attachments/assets/c8269351-18d6-4ae6-a8c7-50f0393ae220">
I also tried this:
<img width="449" alt="Screenshot 2024-08-28 at 5 12 35 PM" src="https://github.com/user-attachments/assets/b05df420-4127-4c60-bc11-0facfee905ba">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 14.6.1 (23G93)
 - Python Version 3.10.13
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
again thanks for reporting! can you send me the config files you have in the `project_folder/configs` directory as a zip and I will take a look?

**Comment by sara-xinyue-liang** [comment]
[configs.zip](https://github.com/user-attachments/files/16790122/configs.zip)
Here is the config file!

Sara Liang

**Comment by sronilsson** [comment]
Thanks Sara - it's odd, I could not reproduce this error, with my configs or yours, but I inserted a couple of rows that should correct for it if it occurs. 

Can you try with simba version 2.0.9 using `pip install simba-uw-tf-dev --upgrade --no-deps` and see how it runs on your end?
