### ISSUE TITLE
Extract Features

### ISSUE THREAD

**Issue by DJang11** [sgoldenlab/simba#60]
Hi, 
After I created a new project, and attempted to "Extract Features", however, instead I received this message on anaconda shell.

Exception in thread Thread-5:
Traceback (most recent call last):
  File "c:\users\jean\anaconda3\envs\simba2\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\jean\anaconda3\envs\simba2\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\jean\anaconda3\envs\simba2\lib\site-packages\simba\SimBA.py", line 4470, in extractfeatures
    extract_features_wotarget_8(self.projectconfigini)
  File "c:\users\jean\anaconda3\envs\simba2\lib\site-packages\simba\features_scripts\extract_features_8bp.py", line 60, in extract_features_wotarget_8
    fps = float(currVideoSettings['fps'])
  File "c:\users\jean\anaconda3\envs\simba2\lib\site-packages\pandas\core\series.py", line 131, in wrapper
    raise TypeError("cannot convert the series to " "{0}".format(str(converter)))
TypeError: cannot convert the series to <class 'float'>

I also got an error on SimBA GUI, so I checked video info on the file, but all seems correct.
![image](https://user-images.githubusercontent.com/62602896/90171133-0993a200-dd6f-11ea-8a22-403b82d97984.png)

One thing I was concerning was that my laptop does not meet the minimum requirement you suggested. (spec is Windows10, 8GB RAM, & i5core). Does this error come due to the insufficient environment?
In addition, I ran this program without GPU, and I have downloaded simba-uw-no-tf.

Best, 
Doyeon Jang

**Comment by sgoldenlab** [comment]
Hi @DJang11! 

Check out this FAQ issue: https://github.com/sgoldenlab/simba/blob/SimBA_no_TF/docs/FAQ.md#when-i-try-to-execute-some-process-in-simba-eg-feature-extraction-or-generate-frames-or-videos-etc-i-get-a-typeerror-that-may-look-somthing-like-this

To understand if what might be happening, could you send me two screenshots, (1) of the content of your `project_filder/csv/outlier_corrected_movement_location` folder, and (2) the content of your `project_folder/logs/video_info.csv` file. That will help me a lot for understanding the issue. 

Thanks!
