### ISSUE TITLE
DLL Error When Attempting to Run SimBA

### ISSUE THREAD

**Issue by MattKDawson** [sgoldenlab/simba#70]
When I attempt to run SimBAxTf in a virtual environment using the Anaconda command prompt, I receive a WinError 126 (see below for the full error readout). I did have some issues with getting SimBA to install and I think that I installed CUDA and cuDNN properly, but either of those may be causing the issues related to my error. Any help or advice you could give me would be extremely appreciated, as my coding experience is limited to basics and I am at a loss as to how to troubleshoot my error.

Thank you!

ERROR READOUT:
(simba_env) C:\Users\carol>simba
Traceback (most recent call last):
  File "c:\users\carol\anaconda3\envs\simba_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\carol\anaconda3\envs\simba_env\Scripts\simba.exe\__main__.py", line 4, in <module>
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 48, in <module>
    from simba.ROI_freehand_draw_3 import roiFreehand
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\ROI_freehand_draw_3.py", line 6, in <module>
    from shapely.geometry import Polygon
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\shapely\geometry\base.py", line 18, in <module>
    from shapely.coords import CoordinateSequence
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
  File "c:\users\carol\anaconda3\envs\simba_env\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by sgoldenlab** [comment]
Hi @MattKDawson - yes this is a common issue, and there should be an easy fix.

1. After activating your `simba_env`, type `pip uninstall shapely`. 

2. Next, type `pip install shapely`. 

3. Then, try booting simba again with `simba`. If that does not work, try `conda install shapely` in step 3 above and see if simba boots by typing `simba`. If that also does not work:

1. Go to this address https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely and download Shapely‑1.7.1‑cp36‑cp36m‑win_amd64.whl

2. Next, with your `simba_env` activated, navigate to your downloads folder (I presume you should type `cd c:\users\carol\Downloads` 

3. Next, type pip install Shapely‑1.7.1‑cp36‑cp36m‑win_amd64.whl

4. Check if SimBA starts by typing `simba`

Let me know if that solves it for you!

**Comment by MattKDawson** [comment]
Hi @sgoldenlab !

Using `conda install shapely` worked! Thank you so much for your help, SimBA will be such a valuable tool for me and my lab.

Take care!
