### ISSUE TITLE
Tkinter Issue - Blank SimBA GUI

### ISSUE THREAD

**Issue by MattKDawson** [sgoldenlab/simba#71]
Hello again @sgoldenlab ! Sorry to be posting another issue for you to deal with but I am having some trouble getting the SimBA GUI to work after installing via `pip install simba-uw-tf`. After creating a new project, when I load the project_config I see the GUI window but all the tabs except ROI are blank (see image below). I also get the following error readout in the Anaconda prompt after loading the project_config:

(simba_env) C:\Users\carol>simba
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\carol\anaconda3\envs\simba_env\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 3256, in <lambda>
    launchloadprojectButton = Button(lpMenu,text='Load Project',command=lambda:self.launch(lpMenu,inputcommand))
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 3267, in launch
    command(self.projectconfigini.file_path)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 3601, in __init__
    self.bp1 = DropDownMenu(label_heatmap,'Bodypart',bpoptions,'15')
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 777, in __init__
    self.popupMenu = OptionMenu(self,self.dropdownvar,*self.choices,command=com)
TypeError: __init__() missing 1 required positional argument: 'value'

Any help and advice you can give me is greatly appreciated! Thank you for your time!

![simba_blank_gui](https://user-images.githubusercontent.com/71152165/95510570-64163c80-0973-11eb-8793-66b5446f9423.png)

**Comment by sgoldenlab** [comment]
@MattKDawson , can you let us know which version of simba you are currently using?  Go to cmd and type ` pip show simba-uw-tf `

Please make sure that you are using the latest version, which is version 1.2.23.

Please let us know if this happens to you on the latest version.

Thanks,
JJ

**Comment by MattKDawson** [comment]
Hi @sgoldenlab ! I am currently using the latest version, 1.2.23, based on the info returned by the `pip show simba-uw-tf` command :)

**Comment by sgoldenlab** [comment]
@MattKDawson - I thought I had sorted this potential issue in an earlier version so surprised to see it return.

Can you install the development version of simba and let me know if the error persists? 

So first `pip uninstall simba-uw-tf`

Then `pip install simba-uw-tf-dev'

then Launch SimBA with `simba` - and see if you encounter the same error loading your project?

**Comment by MattKDawson** [comment]
Hi @sgoldenlab ! I uninstalled `simba-uw-tf` and installed the development version of SimBA, and now see this error readout when attempting to launch SimBA with `simba`:

(simba_env) C:\Users\carol>simba
Traceback (most recent call last):
  File "c:\users\carol\anaconda3\envs\simba_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\carol\anaconda3\envs\simba_env\Scripts\simba.exe\__main__.py", line 4, in <module>
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 44, in <module>
    from simba.train_multiple_models_from_meta import *
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\train_multiple_models_from_meta.py", line 26, in <module>
    import shap
ModuleNotFoundError: No module named 'shap'

**Comment by sgoldenlab** [comment]
Ah

**Comment by sgoldenlab** [comment]
I have to package it with it, I forgot. Try running pip install shap, then start simba.

**Comment by MattKDawson** [comment]
I think that did it! I can now see the GUI. Thank you again for your help!

**Comment by sgoldenlab** [comment]
@MattKDawson if you run into any further issues don't hesitate to open a new issue thread

**Comment by MattKDawson** [comment]
Hi @sgoldenlab ! I actually have another issue when trying to import .SLP files into my project related to Tkinter. When trying to import my .SLP file into my project, I receive the following error readout in the Anaconda prompt:

Traceback (most recent call last):
  File "c:\users\carol\anaconda3\envs\simba_env\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 3048, in importh5
    importSLEAPbottomUP(self.configinifile,self.h5path.folder_path,idlist)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\sleap_bottom_up_convert.py", line 138, in importSLEAPbottomUP
    dataDf.loc[len(dataDf)] = outRow
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\pandas\core\indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\pandas\core\indexing.py", line 406, in _setitem_with_indexer
    return self._setitem_with_indexer_missing(indexer, value)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\pandas\core\indexing.py", line 647, in _setitem_with_indexer_missing
    raise ValueError("cannot set a row with mismatched columns")
ValueError: cannot set a row with mismatched columns

I also see the following message in the main SimBA window at the same time:

Warning: The video name could not be found in the .SLP meta-data table
SimBA therefore gives the imported CSV the same name as the SLP file.
To be sure that SimBAs slp import function works, make sure the .SLP file and the associated video file has the same file name - e.g., "Video1.slp" and "Video1.slp" borefore importing the videos and SLP files to SimBA.

Is this an issue with how my SLEAP model was created, or is this something to do with SimBA? My SLEAP model was mostly just a test and was created with different tracking points than what SimBA expects and was also trained using the top-down training model and not the bottom-up model. Could these be creating this issue?

Thanks! :)
