### ISSUE TITLE
Unable to run RF model. KeyError: Mouse_1_note_to_tail on 'Run RF Model'

### ISSUE THREAD

**Issue by benlansdell** [sgoldenlab/simba#77]
I'm training the RF model to predict behaviors for a 4bp single animal. I.e. Type of tracking: Classic Tracking. Config: 1 animal, 4bp.

I'm using SimBA on linux (the Simba-UW-tf-dev-0.73) branch. 

The pipeline works up until I reach the Run Machine Model section. I can train and validate the model on a single video. When trying to 'Run RF Model', SimBA runs for a brief while then returns the error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/blansdell/anaconda3/envs/dlc/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Mouse_1_nose_to_tail'
```

I don't find Mouse_1_nose_to_tail in the extracted features. I do find 'Mouse_nose_to_tail', however.  So it seems like the feature is not named correctly, but perhaps I'm missing something?

**Comment by sgoldenlab** [comment]
@benlansdell , Hi Ben, I wonder if you can send me one video and the csv tracking data so I can test it out to see where it went wrong?

Please send it to jchoong@uw.edu.

Thanks,

-JJ

**Comment by sgoldenlab** [comment]
@benlansdell Thank you for catching my mistake! You are correct, I messed up the naming. I have fixed this and you can update your simba to version 0.74.1 and see if it works on your end.

Thanks,
JJ

**Comment by benlansdell** [comment]
Hi JJ, 

Yes, that seems to have fixed it. Thank you!
