### ISSUE TITLE
can't run SimBA from repo: missing files

### ISSUE THREAD

**Issue by smidm** [sgoldenlab/simba#97]
**Describe the bug**

The repository version is not usable. Files are missing.

**To Reproduce**
1. git clone repository
2. install dependencies
3. run `simba`
4. fail with
```
Traceback (most recent call last):
  File ".../conda/envs/simba/bin/simba", line 5, in <module>
    from simba.SimBA import main
  File ".../conda/envs/simba/lib/python3.6/site-packages/simba/SimBA.py", line 23, in <module>
    from simba.plotly_create_h5 import *
ModuleNotFoundError: No module named 'simba.plotly_create_h5'
```

**Expected behavior**

SimBA starts

**Desktop (please complete the following information):**
 - OS: Fedora Linux 33
 - Python Version: 3.6.13
 - Are you using anaconda? yes

**Comment by inoejj** [comment]
Please uninstall your current simba and try pip install simba-uw-tf-dev==0.80.8 and see if that fixes your error.

Best,
JJ

**Comment by smidm** [comment]
I have a working SimBA installation. That's not the problem.

I want to make some modifications to the development version of SimBA that is in this repository, but it is missing some files: plotly_create_h5.py, setup.py, ... 

The usual way to contribute to an open source project is to clone a repo, make changes, test them and make a pull request. This is not easy now.

**Comment by inoejj** [comment]
I see, I apologize as I misunderstood what you meant. 

Please try it again and let me know if we are on the same page.

Best,
JJ

**Comment by inoejj** [comment]
Please try it again now :)

**Comment by smidm** [comment]
Thank for the update (including `setup.py`). There are still some files missing:
```
Traceback (most recent call last):
  File "simba.py", line 5, in <module>
    from simba.SimBA import main
  File ".../simba/SimBA.py", line 23, in <module>
    from simba.plotly_create_h5 import *
  File ".../simba/plotly_create_h5.py", line 5, in <module>
    from simba.rw_dfs import *
ModuleNotFoundError: No module named 'simba.rw_dfs'

```

**Comment by inoejj** [comment]
You will have to run your script using cmd on the simba-master directory and call `python App.py`

I think if you do that the error will be gone :)

**Comment by smidm** [comment]
The results are the same. The `simba.py` and `App.py` are doing almost the same.
```
python App.py
Traceback (most recent call last):
  File "App.py", line 2, in <module>
    from simba.SimBA import main as App
  File ".../simba/SimBA.py", line 23, in <module>
    from simba.plotly_create_h5 import *
  File ".../simba/plotly_create_h5.py", line 5, in <module>
    from simba.rw_dfs import *
ModuleNotFoundError: No module named 'simba.rw_dfs'
```
There is still a lot of differences between the packaged SimBA and the git repo:

```
$ diff -q simba-git/ simba-pip/ | grep -v differ | grep -v 'Common subdirectories'  | sort

Only in simba-pip/: append_boris.py
Only in simba-pip/: extract_frames_fast.py
Only in simba-pip/: import_solomon.py
Only in simba-pip/: Kleinberg_burst_analysis.py
Only in simba-pip/: path_plot_new.py
Only in simba-pip/: pose_configurations_archive
Only in simba-pip/: process_movement_new.py
Only in simba-pip/: process_videos_automation_linux.py
Only in simba-pip/: process_videos_automation_win.py
Only in simba-pip/: reverse_tracking_order.py
Only in simba-pip/: ROI_add_to_features_old2.py
Only in simba-pip/: ROI_add_to_features_old.py
Only in simba-pip/: ROI_analysis_old.py
Only in simba-pip/: ROI_analysis.py
Only in simba-pip/: ROI_directionality_to_other_animals.py
Only in simba-pip/: ROI_directionality_to_other_animals_visualize.py
Only in simba-pip/: ROI_plot_multi_process.py
Only in simba-pip/: ROI_plot_old_2.py
Only in simba-pip/: ROI_plot_old.py
Only in simba-pip/: ROI_process_movement_old.py
Only in simba-pip/: run_dash_tkinter.py
Only in simba-pip/: run_RF_model_old.py
Only in simba-pip/: rw_dfs.py
Only in simba-pip/: SimBA_dash_app.py

Only in simba-git/: classifier_validation.py
Only in simba-git/: correct_devs_loc.py
Only in simba-git/: correct_devs_mov.py
Only in simba-git/: crop_video_tool_user_bounding_box_multiple.py
Only in simba-git/: extract_features_with_scaling.py
Only in simba-git/: extract_features_wo_targets.py
Only in simba-git/: gantt_old.py
Only in simba-git/: golden_lab.ico
Only in simba-git/: image.png
Only in simba-git/: mouse_diagrams
Only in simba-git/: next_clahe.py
Only in simba-git/: next_greyscale.py
Only in simba-git/: next_superimposeframe.py
Only in simba-git/: plot_heatmap_location.py
Only in simba-git/: plot_heatmap_old.py
Only in simba-git/: plot_sklearn_results.py
Only in simba-git/: process_data_log_old.py
Only in simba-git/: process_movement_old.py
Only in simba-git/: tkinter_class_test_efficient_scratch.py
Only in simba-git/: validate_model_on_single_video_copy.py
```
(listing just files that are unique in one of sources)

**Comment by smidm** [comment]
The listing above are differences between `simba-uw-tf` and github master.

Here is `Simba_UW_tf_dev` and github master (including subfolders):

```
$ diff -qr simba-github-master/simba Simba_UW_tf_dev -x '*pyc' -x __pycache__ | grep Only | sort

Only in simba-github-master/simba: classifier_validation.py
Only in simba-github-master/simba: extract_features_with_scaling.py
Only in simba-github-master/simba: extract_features_wo_targets.py
Only in simba-github-master/simba/features_scripts: extract_features_16b-8extra.py
Only in simba-github-master/simba: golden_lab.ico
Only in simba-github-master/simba: image.png
Only in simba-github-master/simba: mouse_diagrams
Only in simba-github-master/simba: next_clahe.py
Only in simba-github-master/simba: next_greyscale.py
Only in simba-github-master/simba: next_superimposeframe.py
Only in simba-github-master/simba: plot_sklearn_results.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_14_16bp.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_2_maDLC.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_4bp.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_7_8bp.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_9bp.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_plot_features.py
Only in simba-github-master/simba/sklearn_plot_scripts: plot_sklearn_results_user_defined.py
Only in simba-github-master/simba: tkinter_class_test_efficient_scratch.py
Only in simba-github-master/simba: validate_model_on_single_video_copy.py

Only in Simba_UW_tf_dev: append_boris.py
Only in Simba_UW_tf_dev/assets: ._dash_simba_base.css
Only in Simba_UW_tf_dev: combine_to_h5.py
Only in Simba_UW_tf_dev: dash_simba.css
Only in Simba_UW_tf_dev: ._.DS_Store
Only in Simba_UW_tf_dev: .DS_Store
Only in Simba_UW_tf_dev: extract_frames_fast.py
Only in Simba_UW_tf_dev: fast_video.py
Only in Simba_UW_tf_dev/features_scripts: extract_features_16bp_new_2.py
Only in Simba_UW_tf_dev: FSTCC.py
Only in Simba_UW_tf_dev: gantt_video.py
Only in Simba_UW_tf_dev: .idea
Only in Simba_UW_tf_dev: import_solomon.py
Only in Simba_UW_tf_dev: Initate_multi_process.py
Only in Simba_UW_tf_dev: Kleinberg_burst_analysis.py
Only in Simba_UW_tf_dev/outlier_scripts: .idea
Only in Simba_UW_tf_dev/outlier_scripts/location: .idea
Only in Simba_UW_tf_dev/outlier_scripts/movement: correct_devs_mov_15bp.py
Only in Simba_UW_tf_dev/outlier_scripts/movement: correct_devs_mov_user_defined_new.py
Only in Simba_UW_tf_dev/outlier_scripts/movement: correct_devs_mov_user_defined_old.py
Only in Simba_UW_tf_dev/outlier_scripts/movement: .idea
Only in Simba_UW_tf_dev/outlier_scripts/movement: rw_dfs.py
Only in Simba_UW_tf_dev/outlier_scripts: rw_dfs.py
Only in Simba_UW_tf_dev: path_plot_new.py
Only in Simba_UW_tf_dev: pose_configurations_archive
Only in Simba_UW_tf_dev/pose_configurations/schematics: Picture13.png
Only in Simba_UW_tf_dev: process_movement_new.py
Only in Simba_UW_tf_dev: process_videos_automation_linux.py
Only in Simba_UW_tf_dev: process_videos_automation_win.py
Only in Simba_UW_tf_dev: pup_retrieval_1.py
Only in Simba_UW_tf_dev: reverse_tracking_order.py
Only in Simba_UW_tf_dev: ROI_add_to_features_old2.py
Only in Simba_UW_tf_dev: ROI_add_to_features_old.py
Only in Simba_UW_tf_dev: ROI_analysis_old.py
Only in Simba_UW_tf_dev: ROI_analysis.py
Only in Simba_UW_tf_dev: ROI_directionality_to_other_animals.py
Only in Simba_UW_tf_dev: ROI_directionality_to_other_animals_visualize.py
Only in Simba_UW_tf_dev: ROI_plot_multi_process.py
Only in Simba_UW_tf_dev: ROI_plot_new.py
Only in Simba_UW_tf_dev: ROI_plot_old_2.py
Only in Simba_UW_tf_dev: ROI_plot_old.py
Only in Simba_UW_tf_dev: ROI_process_movement_old.py
Only in Simba_UW_tf_dev: run_dash_tkinter.py
Only in Simba_UW_tf_dev: run_RF_model_old.py
Only in Simba_UW_tf_dev: rw_dfs.py
Only in Simba_UW_tf_dev: SimBA_dash_app.py
Only in Simba_UW_tf_dev/sklearn_plot_scripts: .idea
Only in Simba_UW_tf_dev: timeBins_classifiers_new.py

```
